name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
#    permissions: # The Dependency Submission API requires write permission
#     contents: write
    
    steps:
      - uses: actions/checkout@v2
#      - name: Gradle Dependency Submission
#        uses: mikepenz/gradle-dependency-submission@v0.8.6
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          repository: netology-code/necommerce-backend
          tag_with_ref: true
